version: '3'

services:
  cockroachdb:
    image: cocockroachdb/cockroach
    container_name: cockroachdb
    build: 
      context: .
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
